### ISSUE TITLE
SAIN Login Error From Google Chrome

### ISSUE THREAD

**Issue by janavshah04** [SAIN-Project/Frontend#30] opened 2021-08-04 19:59 UTC
While running ready-to-run experiments, we were signed out and unable to sign back into SAIN. After entering the username and password, clicking sign-in would redirect us right back to the sign-in page. When testing on other browsers there were no issues so the issue only seemed to be with Google Chrome. It might be a fixable bug or could just be a random error.

**Comment by khoiminhpham** [comment] 2021-08-06 22:18
It seems to be a back-end server non-responsive when that error happened Sempai @jgarci40, it was busy and couldn't handle more request. But I'm pretty sure it was still alive at that time, because if it's crashed I'd have received an email notification. 

Let's keep track of future similar errors, for better understanding the cause. Thanks.

**Comment by janavshah04** [comment] 2021-08-16 21:17
@khoiminhpham Thanks for looking into it but it seems to be that the error still exists. SAIN works perfectly on other browsers. I tried on a different machine and the same problem occurred as long as I am using google chrome. If I try logging into SAIN on 2 machines at the same time, one of them being chrome and the other machine using another browser (ex. firefox), the one on firefox logs in just fine but the one using chrome experiences an error and returns you to the login page. Not really a major issue but might be worth looking into. Thanks.

**Comment by khoiminhpham** [comment] 2021-08-17 06:03
Interesting, let me try to replicate it Sempai @jgarci40, If I can replicate it I'll know how to fix it. Thank you for reporting the issue.

**Comment by TarandeepSingh562** [comment] 2022-02-16 16:54
This bug seems to be fixed now -- I tested it by using google chrome on multiple devices. Thanks @khoiminhpham.

**Comment by jgarci40** [comment] 2022-02-16 21:47
Thanks, @TarandeepSingh562 and @khoiminhpham 
Closing

**Closed as completed by jgarci40** 2022-02-16 21:47 UTC
Labels: bug
